data_cfg:
  dataset_name: Gait3D
  dataset_root: 
  dataset_partition: ./datasets/Gait3D/Gait3D.json
  test_dataset_name: Gait3D
  num_workers: 1
  remove_no_gallery: false

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 60000
  save_name: GPGait_PlusPlus
  eval_func: evaluate_Gait3D
  sampler:
    batch_size: 4 # should same to num_gpus
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  transform:
    - type: Compose
      trf_cfg:
        - type: Affine
        - type: RescaleCenter
        - type: HOD_MultiInput
          joint_format: coco
        - type: SkeletonInput

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.3
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: GPGait_PlusPlus
  in_channels:
    - 2 
    - 64
    - 64
    - 128
    - 128
    - 256
  num_class: 3000
  share_num: 3
  mask: false

optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.00002

scheduler_cfg:
  three_phase: True
  max_lr: 0.001
  div_factor: 100
  total_steps: 60000
  pct_start: 0.475
  scheduler: OneCycleLR

trainer_cfg:
  enable_float16: false
  log_iter: 100
  with_test: false
  restore_ckpt_strict: false
  restore_hint: 0
  save_iter: 10000
  save_name: GPGait_PlusPlus-loss
  sync_BN: true
  total_iter: 60000
  sampler:
    batch_shuffle: false
    batch_size:
      - 32
      - 4
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_ordered
    frames_skip_num: 2
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: Affine
        - type: RescaleCenter
        - type: HOD_MultiInput
          joint_format: coco
        - type: SkeletonInput
